
import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    code: "GL-100",
    name: "Guants de Làtex",
    description: "Caixa de 100 guants d'examinació de làtex",
    category: "Seguretat",
    image: "/placeholder.svg",
    price: 0,
    stock: 500,
  },
  {
    id: "2",
    code: "PP-500",
    name: "Paper d'Impressora",
    description: "500 fulls de paper d'alta qualitat",
    category: "Paper",
    image: "/placeholder.svg",
    price: 0,
    stock: 1000,
  },
  {
    id: "3",
    code: "BP-012",
    name: "Bolígrafs",
    description: "Paquet de 12 bolígrafs blaus",
    category: "Escriptura",
    image: "/placeholder.svg",
    price: 0,
    stock: 200,
  },
  {
    id: "4",
    code: "MQ-050",
    name: "Mascaretes Quirúrgiques",
    description: "Caixa de 50 mascaretes quirúrgiques d'un sol ús",
    category: "Seguretat",
    image: "/placeholder.svg",
    price: 0,
    stock: 300,
  },
  {
    id: "5",
    code: "GH-500",
    name: "Gel Hidroalcohòlic",
    description: "500ml de gel hidroalcohòlic de grau mèdic",
    category: "Seguretat",
    image: "/placeholder.svg",
    price: 0,
    stock: 400,
  },
  {
    id: "6",
    code: "NA-012",
    name: "Notes Adhesives",
    description: "Paquet de 12 blocs de notes adhesives",
    category: "Paper",
    image: "/placeholder.svg",
    price: 0,
    stock: 150,
  },
  {
    id: "7",
    code: "PC-500",
    name: "Paper de Còpia Premium",
    description: "Paper de còpia d'alta qualitat per a impressió professional",
    category: "Paper",
    image: "/placeholder.svg",
    price: 0,
    stock: 800,
  },
  {
    id: "8",
    code: "PF-020",
    name: "Pantalles Facials",
    description: "Paquet de 20 pantalles facials de grau mèdic",
    category: "Seguretat",
    image: "/placeholder.svg",
    price: 0,
    stock: 150,
  },
  {
    id: "9",
    code: "RG-024",
    name: "Retoladors de Gel",
    description: "Conjunt de 24 retoladors de gel de colors",
    category: "Escriptura",
    image: "/placeholder.svg",
    price: 0,
    stock: 300,
  },
  {
    id: "10",
    code: "BS-010",
    name: "Bates d'un Sol Ús",
    description: "Paquet de 10 bates mèdiques d'un sol ús",
    category: "Seguretat",
    image: "/placeholder.svg",
    price: 0,
    stock: 200,
  },
  {
    id: "11",
    code: "GP-001",
    name: "Grapadora",
    description: "Grapadora professional amb 1000 grapes",
    category: "Oficina",
    image: "/placeholder.svg",
    price: 0,
    stock: 150,
  },
  {
    id: "12",
    code: "CA-100",
    name: "Carpetes",
    description: "Paquet de 100 carpetes mida carta",
    category: "Paper",
    image: "/placeholder.svg",
    price: 0,
    stock: 400,
  }
];

export const categories = [...new Set(products.map((p) => p.category))];
