apiVersion: v1
kind: Secret
metadata:
  name: matofi-postgres-secret
  namespace: matofi
type: Opaque
data:
  POSTGRES_DB: 'bWF0b2ZpX2Ri'  #matofi_db
  POSTGRES_USER: 'bWF0b2ZpdXNlcg=='  #matofiuser
  POSTGRES_PASSWORD: 'U2VjdXJlUGFzczEyMw==' #SecurePass123
  POSTGRES_HOST: 'bWF0b2ZpLXBvc3RncmVz'  # matofi-postgres (nombre del servicio)
  POSTGRES_PORT: 'NTQzMg=='  # 5432 en Base64
